spring:
  datasource:
    url: jdbc:postgresql://database-station-1.cbaqou6cmbcu.ap-south-1.rds.amazonaws.com/capstone
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

# comments
